name: salon_queue_and_service_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dio: ^5.3.2
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  fl_chart: ^0.64.0
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  connectivity_plus: ^5.0.1
  permission_handler: ^11.0.1
  flutter_local_notifications: ^16.1.0
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  http: ^1.1.0
  url_launcher: ^6.2.1
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
